# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [21]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [22]:
# Import torch
import torch

# Create random tensor
t1 = torch.rand(size=(7, 7))
t1

tensor([[0.8728, 0.0232, 0.2130, 0.6687, 0.5091, 0.1971, 0.2547],
        [0.8265, 0.5685, 0.3475, 0.6461, 0.8973, 0.2314, 0.0324],
        [0.0527, 0.0400, 0.7671, 0.8389, 0.1016, 0.5950, 0.8977],
        [0.8680, 0.8673, 0.1164, 0.9057, 0.8049, 0.8156, 0.7367],
        [0.6933, 0.4859, 0.7392, 0.7935, 0.5785, 0.7716, 0.2591],
        [0.1253, 0.5539, 0.8235, 0.2726, 0.4316, 0.8501, 0.6799],
        [0.5708, 0.6880, 0.7709, 0.4538, 0.7669, 0.8060, 0.6506]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [23]:
# Create another random tensor
t2 = torch.rand(size=(1, 7))
# Perform matrix multiplication 
t1 * t2

tensor([[0.6092, 0.0010, 0.0702, 0.3554, 0.2484, 0.0184, 0.1101],
        [0.5768, 0.0251, 0.1146, 0.3434, 0.4378, 0.0216, 0.0140],
        [0.0367, 0.0018, 0.2529, 0.4459, 0.0496, 0.0556, 0.3882],
        [0.6058, 0.0384, 0.0384, 0.4814, 0.3928, 0.0762, 0.3186],
        [0.4839, 0.0215, 0.2437, 0.4217, 0.2823, 0.0721, 0.1121],
        [0.0875, 0.0245, 0.2715, 0.1449, 0.2106, 0.0794, 0.2940],
        [0.3984, 0.0304, 0.2542, 0.2412, 0.3742, 0.0753, 0.2814]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t1 = torch.rand(size=(7, 7))
t2 = torch.rand(size=(1, 7))

# Matrix multiply tensors
t1 * t2

tensor([[0.2392, 0.6298, 0.0882, 0.0922, 0.1745, 0.5296, 0.1008],
        [0.4320, 0.3735, 0.6305, 0.2437, 0.2280, 0.0186, 0.0347],
        [0.1416, 0.4251, 0.6956, 0.5588, 0.0914, 0.2358, 0.1401],
        [0.4411, 0.3255, 0.8716, 0.2929, 0.3138, 0.7958, 0.0074],
        [0.0893, 0.3061, 0.3042, 0.6509, 0.0998, 0.2254, 0.0310],
        [0.0153, 0.1706, 0.9271, 0.5050, 0.4213, 0.4396, 0.0501],
        [0.2817, 0.0272, 0.1383, 0.1692, 0.4628, 0.6625, 0.0572]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [25]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [26]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [27]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [28]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [29]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [30]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
